# Generated by Django 5.0.1 on 2024-01-31 18:40

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "about_me",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="About me"
                    ),
                ),
                (
                    "prifile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_photos",
                        verbose_name="Profile photo",
                    ),
                ),
                ("is_buyer", models.BooleanField(default=False, verbose_name="Buyer")),
                (
                    "is_seller",
                    models.BooleanField(default=False, verbose_name="Seller"),
                ),
                ("is_agent", models.BooleanField(default=False, verbose_name="Agent")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Rating"
                    ),
                ),
                (
                    "nb_views",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Number of views"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
