# Generated by Django 5.0.1 on 2024-01-31 18:46

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="FR", max_length=2, verbose_name="Country"
            ),
        ),
    ]
