# Generated by Django 5.0.1 on 2024-01-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="Rating"
            ),
        ),
    ]
