# Generated by Django 5.0.1 on 2024-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="nb_views",
        ),
        migrations.AddField(
            model_name="profile",
            name="nb_reviews",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Number of reviews"
            ),
        ),
    ]
