# Generated by Django 5.0.1 on 2024-02-01 16:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_profile_nb_views_profile_nb_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=30, region=None, verbose_name="Phone number"
            ),
        ),
    ]
