# Generated by Django 5.0.1 on 2024-01-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="date_join",
            new_name="date_joined",
        ),
    ]
