# Generated by Django 5.0.1 on 2024-02-01 16:46

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property-photos/%Y/%m/%d")),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPublishManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        max_length=200,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Reference ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="FR", max_length=2, verbose_name="Country"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                ("zipcode", models.CharField(max_length=20, verbose_name="zipcode")),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("For sale", "For sale"), ("For rent", "For rent")],
                        default="For sale",
                        max_length=50,
                        verbose_name="Sale Type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("bedrooms", models.IntegerField(verbose_name="Bedrooms")),
                ("bathrooms", models.IntegerField(verbose_name="Bathrooms")),
                (
                    "house_type",
                    models.CharField(
                        choices=[
                            ("Maison", "Maison"),
                            ("Apartment", "Apartment"),
                            ("Villa", "Villa"),
                            ("Office", "Office"),
                            ("Commerce", "Commerce"),
                            ("Other", "Other"),
                        ],
                        default="Apartment",
                        max_length=50,
                        verbose_name="House Type",
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Surface"
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Views")),
                (
                    "list_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "image",
                    models.ManyToManyField(
                        blank=True,
                        related_name="properties",
                        to="properties.listingimage",
                        verbose_name="Images",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="agent_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent, Seller, Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.AddField(
            model_name="listingimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.property"
            ),
        ),
    ]
