# Generated by Django 5.0.1 on 2024-02-02 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="IP Address")),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_views",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Property View",
                "verbose_name_plural": "Total Property Views",
            },
        ),
    ]
